FROM fedora
MAINTAINER JL

CMD ["bash"]

RUN yum -y install \
  bash-completion \
  zip \
  htop \
  iftop \
  iotop \
  sysstat \
  net-tools \
  iputils \
  fping \
  traceroute \
  nmap \
  tcpdump \
  telnet \
  mtr \
  iperf \
  omping \
  sockperf \
  python \
  httpd-tools \
  systemtap \
  perf \
  clang \
  at \
  && yum clean all
