FROM fedora
MAINTAINER JL

CMD ["bash"]

RUN yum -y install \
  bash-completion \
  zip \
  htop \
  iftop \
  iotop \
  sysstat \
  net-tools \
  iputils \
  traceroute \
  nmap \
  tcpdump \
  && yum clean all
